// List of Indian names
var nameList = [
  "Aadarsh",
  "Aakash",
  "Abhinav",
  "Abhishek",
  "Abraham",
  "Adarsh",
  "Aditya",
  "Alok",
  "Amit",
  "Ananthu",
  "Anil",
  "Ankit",
  "Ankur",
  "Arjun",
  "Ashok",
  "Ashutosh",
  "Atul",
  "Ayush",
  "Bala",
  "Balakrishnan",
  "Balram",
  "Bansi",
  "Bharat",
  "Bhavesh",
  "Bhoomika",
  "Chandan",
  "Chandni",
  "Chetan",
  "Chinmay",
  "Chitranshu",
  "Daksh",
  "Damodar",
  "Deepak",
  "Devesh",
  "Dhruv",
  "Divya",
  "Dinesh",
  "Divyaansh",
  "Diksha",
  "Dinesh",
  "Dipak",
  "Esha",
  "Gagan",
  "Ganesh",
  "Gautam",
  "Gourav",
  "Harish",
  "Harsh",
  "Hemant",
  "Himanshu",
  "Ishaan",
  "Ishwar",
  "Jagdish",
  "Jai",
  "Jatin",
  "Jay",
  "Jayant",
  "Jayesh",
  "Jayprakash",
  "Kailash",
  "Kamal",
  "Karan",
  "Kartik",
  "Karthik",
  "Kavya",
  "Kiran",
  "Koushik",
  "Krishan",
  "Lakshmi",
  "Mahendra",
  "Manoj",
  "Manish",
  "Mansi",
  "Meena",
  "Megha",
  "Mohan",
  "Mohit",
  "Nandan",
  "Naveen",
  "Neha",
  "Nikhil",
  "Nikita",
  "Niranjan",
  "Nitin",
  "Pallavi",
  "Pankaj",
  "Paras",
  "Parikshit",
  "Pradeep",
  "Prakash",
  "Praveen",
  "Priya",
  "Rahul",
  "Rajat",
  "Rakesh",
  "Raman",
  "Ramesh",
  "Ravi",
  "Reema",
  "Ritesh",
  "Rohan",
  "Sachin",
  "Sadaf",
  "Sagar",
  "Sahil",
  "Saket",
  "Samir",
  "Sandeep",
  "Sangeetha",
  "Sanjay",
  "Saroj",
  "Shailendra",
  "Sham",
  "Shantanu",
  "Shashank",
  "Shiv",
  "Shobha",
  "Shreya",
  "Shruti",
  "Siddharth",
  "Sneha",
  "Sourabh",
  "Soumya",
  "Sudhir",
  "Suman",
  "Sunil",
  "Suraj",
  "Swathi",
  "Tanuja",
  "Tarun",
  "Teena",
  "Uma",
  "Umesh",
  "Vasudha",
  "Venkat",
  "Vidya",
  "Vijay",
  "Vimal",
  "Vinay",
  "Vishal",
  "Yamini",
  "Yash",
  "Yogesh",
  "Yuvraj",
];

const messages = [
  "When this will be releasing",
  "Wow, amazing gameplay!",
  "क्या बात है! मजा आ गया!",
  "Can you play that song again?",
  "No spoilers please!",
  "Which game is this?",
  "कौन जीत रहा है अभी?",
  "This stream is lit!",
  "Best stream ever!",
  "How do you do that?",
  "Come on, you got this!",
  "Nice shot!",
  "गज़ब का मूव था!",
  "Can you shout out my name?",
  "What's your next move?",
  "LOL, that was hilarious!",
  "Love your content!",
  "जबर्दस्त!",
  "Please say hi to me!",
  "How can I join the game?",
  "That's a pro move!",
  "अरे वाह, क्या बात है!",
  "So intense right now!",
  "Can you do a giveaway?",
  "What’s the next stream about?",
  "That was epic!",
  "लगता है कुछ बड़ा होने वाला है!",
  "Can you read my comment?",
  "This chat is crazy!",
  "Amazing skills!",
  "Please reply to my comment.",
  "Go for the win!",
  "इससे बेहतर कुछ नहीं हो सकता!",
  "What's your strategy?",
  "Love from India!",
  "How long have you been streaming?",
  "ये बहुत मजेदार था!",
  "Keep it up!",
  "Is there a delay in the stream?",
  "That’s my favorite game!",
  "क्या कोई और भी ये देख रहा है?",
  "Where are you from?",
  "Teach us how to play like you!",
  "Such a great stream!",
  "क्या आपने वो देखा?",
  "I can’t believe you did that!",
  "What's your setup?",
  "Bhai, tu toh chha gaya!",
  "Any tips for beginners?",
  "This is my first time watching!",
  "This community is awesome!",
  "Nice strategy!",
  "Great teamwork!",
  "क्या लाइव मैच चल रहा है?",
  "I'm so hyped for this!",
  "That was close!",
  "आपका स्ट्रीम बहुत अच्छा है!",
  "Who's your favorite player?",
  "How do you stay so calm?",
  "This is so much fun!",
  "आपका गेमप्ले लाजवाब है!",
  "I love this channel!",
  "What’s your secret?",
  "That was so cool!",
  "क्या आप मुझसे बात कर सकते हैं?",
  "I’m learning a lot from you!",
  "Best moment ever!",
  "कैसे किया आपने?",
  "What a comeback!",
  "Keep streaming!",
  "ऐसा कौन कर सकता है?",
  "This is legendary!",
  "Stream quality is top-notch!",
  "आपका सेटअप क्या है?",
  "Can you do a Q&A?",
  "That was a clutch move!",
  "आपका फेवरेट गेम कौन सा है?",
  "I’m hooked!",
  "Is this your full-time job?",
  "आपका वीडियो बहुत अच्छे हैं!",
  "That was unexpected!",
  "When is your next stream?",
  "आपने वो कैसे किया?",
  "I can't stop watching!",
  "आप बहुत अच्छे हैं!",
  "So many viewers today!",
  "I love your energy!",
  "आपके वीडियो सबसे अच्छे हैं!",
  "This is pure entertainment!",
  "आपसे मिलकर अच्छा लगा!",
  "Your reaction was priceless!",
  "Can you show us your setup?",
  "आपका चैनल बहुत अच्छा है!",
  "That was a great save!",
  "This is my favorite stream!",
  "कौन कौन लाइव देख रहा है?",
  "I’m sharing this stream!",
  "How can I improve my game?",
  "Your commentary is the best!",
  "आपका फेवरेट मूव कौन सा है?",
  "What’s your next goal?",
  "I can’t wait for the next stream!",
];

// Function to generate a random name from the list
export function generateRandomName() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}
// Function to generate a random message from the list
export function generateRandomMessage() {
  return messages[Math.floor(Math.random() * messages.length)];
}

export const formatNumber = (num) => {
  if (num >= 1000000) {
    return `${(num / 1000000).toFixed(1)}M`;
  } else if (num >= 1000) {
    return `${(num / 1000).toFixed(1)}K`;
  } else {
    return num;
  }
};